name: End-to-end tests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get git output names
        id: git
        shell: bash
        run: |
          if [ -d "./jenkins-lib"* ]; then
            echo "UPdaating submodule"
          else
            echo "Adding submodule"
            git submodule add https://oauth2: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@github.com/78mohamed/gitactions-try.git 
            git submodule update --init --recursive
            files=$(ls -A)
            for file in $files; do
              echo "$file"
            done
          fi
          git config --global user.email "mohamed.mansour98.54@gmail.com"
          git config --global user.name "78mohamed"
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
